### ISSUE TITLE
`:stream_not_found` is not handled properly

### ISSUE THREAD

**Issue by feynmanliang** [slashdotdash/commanded-extreme-adapter#2]
It seems like `{:error, :stream_not_found}` is wrapped within a stream, causing the first pattern of https://github.com/slashdotdash/commanded/blob/e96628253b70bec7ded3200e5efb6c2e0a6ebf19/lib/commanded/aggregates/aggregate.ex#L104 to not match

```
iex(1)> Cqrs.Router.dispatch(%Cqrs.Commands.OpenAccount{account_number: "abc", initial_balance: 123})
[debug] starting aggregate process for `Cqrs.Domain.BankAccount` with UUID "abc"
{:error, :aggregate_execution_failed}
iex(2)> [error] GenServer {:aggregate_registry, "abc"} terminating
** (FunctionClauseError) no function clause matching in Commanded.Event.Mapper.map_from_recorded_event/1
    (commanded) lib/commanded/event/mapper.ex:33: Commanded.Event.Mapper.map_from_recorded_event({:error, :stream_not_found})
    (commanded) lib/commanded/aggregates/aggregate.ex:112: anonymous fn/1 in Commanded.Aggregates.Aggregate.rebuild_from_events/1
    (elixir) lib/stream.ex:495: anonymous fn/4 in Stream.map/2
    (elixir) lib/stream.ex:1259: Stream.do_resource/5
    (elixir) lib/stream.ex:1405: Enumerable.Stream.do_each/4
    (elixir) lib/stream.ex:785: Stream.do_transform/8
    (elixir) lib/enum.ex:1776: Enum.take/2
    (elixir) lib/stream.ex:642: anonymous fn/4 in Stream.take/2
Last message: {:"$gen_cast", {:populate_aggregate_state}}
State: %Commanded.Aggregates.Aggregate{aggregate_module: Cqrs.Domain.BankAccount, aggregate_state: nil, aggregate_uuid: "abc", aggregate_version: 0}
[error] Task #PID<0.415.0> started from #PID<0.408.0> terminating
** (stop) exited in: GenServer.call({:via, Registry, {:aggregate_registry, "abc"}}, {:execute_command, Cqrs.Handlers.OpenAccountHandler, :handle, %Cqrs.Commands.OpenAccount{account_number: "abc", initial_balance: 123}}, 5000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Commanded.Event.Mapper.map_from_recorded_event/1
            (commanded) lib/commanded/event/mapper.ex:33: Commanded.Event.Mapper.map_from_recorded_event({:error, :stream_not_found})
            (commanded) lib/commanded/aggregates/aggregate.ex:112: anonymous fn/1 in Commanded.Aggregates.Aggregate.rebuild_from_events/1
            (elixir) lib/stream.ex:495: anonymous fn/4 in Stream.map/2
            (elixir) lib/stream.ex:1259: Stream.do_resource/5
            (elixir) lib/stream.ex:1405: Enumerable.Stream.do_each/4
            (elixir) lib/stream.ex:785: Stream.do_transform/8
            (elixir) lib/enum.ex:1776: Enum.take/2
            (elixir) lib/stream.ex:642: anonymous fn/4 in Stream.take/2
    (elixir) lib/gen_server.ex:737: GenServer.call/3
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: &Commanded.Aggregates.Aggregate.execute/5
    Args: ["abc", %Cqrs.Commands.OpenAccount{account_number: "abc", initial_balance: 123}, Cqrs.Handlers.OpenAccountHandler, :handle, 5000]
```

**Comment by slashdotdash** [comment]
Thanks for spotting this issue, looks like a bug for me to fix.

**Comment by slashdotdash** [comment]
@feynmanliang I've pushed a fix for this issue, let me know if you encounter any problems.

**Comment by feynmanliang** [comment]
Yep, this works now, thanks!

**Comment by slashdotdash** [comment]
@feynmanliang That's great. 

I've also created a barebones example Elixir application for Commanded and the Extreme adapter to use Greg Young's Event Store: [commanded-extreme-example](https://github.com/slashdotdash/commanded-extreme-example)

Let me know if you encounter any further issues, or have any feedback.
